### ISSUE TITLE
Which tf version?

### ISSUE THREAD

**Issue by Theodoric008** [martius-lab/l4-optimizer#1]
I just tried this opt on my tf models, and it reported a bug.
Which tensorflow version should I use?

**Comment by martius-lab** [comment]
Sorry about the bug, it was probably the tf.AUTO_REUSE which was introduced in v1.5. So yes >=1.5 should be fine. We will look into ensuring more backwards compatibility.

**Comment by Theodoric008** [comment]
thanks
