### ISSUE TITLE
SGD+Momentum still beats L4 in my exps

### ISSUE THREAD

**Issue by ankurhanda** [martius-lab/l4-optimizer#2]
I have been doing large scale experiments on SceneNet RGB-D dataset https://robotvault.bitbucket.io/scenenet-rgbd.html. The orange one is SGD+Mom while the other two are L4 with fraction 0.25 (dark blue) and 0.15 (sky blue). Have you tried such large scale datasets and observed something similar? Or do you recommend changing anything that I may have done wrong so L4 shows more promising results

code: https://github.com/ankurhanda/tf-unet/blob/master/train_u-net_horovod.py and https://github.com/ankurhanda/tf-unet/blob/master/UNet.py 

<img width="370" alt="screen shot 2018-02-24 at 11 43 12" src="https://user-images.githubusercontent.com/686480/36630063-1f3e00f6-1958-11e8-8e0d-f2f326a6e184.png">

**Comment by martius-lab** [comment]
Thanks for trying out our code! We 'only' ran it on the datasets in the paper (since we wanted to avoid cherry-picking which results we use in the publication). So from looking at the plots, it seems that the losses for both 0.15 an 0.25 tend to explode sometimes. In this case, I would suggest going a bit lower (0.10 sounds about right).

**Comment by martius-lab** [comment]
I know that this is no more the default setting but maybe the variety of datasets is just too large to hope for a universal default. I hope this will work for you, the other outcome would be disappointing :(. Please, let us know, we will be happy to help!

**Comment by ankurhanda** [comment]
Thanks Martius for your kind reply. Yes, I used default settings and only changed fraction 0.15 and 0.25 and I observed the loss bounces at times so trying out 0.10 might be another option - I can give it a try and see how things go. I think trying on 5M image dataset definitely stress tests the system so would be great to find out why it works or otherwise.

**Comment by ankurhanda** [comment]
same story unfortunately with 0.10 as well. 
<img width="369" alt="screen shot 2018-02-27 at 10 52 58" src="https://user-images.githubusercontent.com/686480/36724883-773e602e-1bac-11e8-96e8-d5b0c532a2f8.png"> 

If I reduced it more I think convergence will get even slower. The skyblue line in SGD+Momentum while pink is L4. If you find time please try this dataset - it is huge and I think that will stress-test your optimiser.

**Comment by martius-lab** [comment]
Thanks for the stress testing :).

Hm... One thing still confuses me. It seems that both L4 and the baseline improved their loss compared to the plots above (but you say 'even slower'). Was there some modification?

**Comment by ankurhanda** [comment]
I started using focal loss - that was better than cross entropy hence better losses. 
Focal Loss: https://arxiv.org/abs/1708.02002

**Comment by martius-lab** [comment]
I saw in your commits that you are switching to yet smaller values of 'fraction'. That's also what I would try doing since there is still a lot of variance in the pink curve.

**Comment by ankurhanda** [comment]
smaller alpha means slow convergence that's why i didn't decrease more.
