### ISSUE TITLE
the classical adam is performing way better then L4Adam

### ISSUE THREAD

**Issue by Oussamab21** [martius-lab/l4-optimizer#5]
I am working on  obstacle detection  for self driving cars using this method  
https://github.com/kujason/avod 

and L4Adam is kinda of getting stuck some where or something else  since the precision is less then 1% and the loss is around 7 or 8 in avrage do you have an idea why this happens ? (I mean is there any other reason beside the value of Alpha ) ?

**Comment by mrolinek** [comment]
Hello, thanks a lot for trying our code and sorry the answer took us forever.

I am afraid we do not have a good answer. The reality of the situation seems to be that L4 has a high variance in performance. Sometimes it is great, sometimes not at all. In some cases, we understood the reasons, more often we did not.
